spring:
  datasource:
    url: jdbc:h2:mem:mylist_db.h2.db
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      #      http://localhost:8080/h2-console
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false